# A Travis CI configuration file.

sudo: required

language: scala

services:
  - docker

notifications:
  email: false

before_install:
  - ./tools/build/scanCode.sh
  - ./tools/travis/setup.sh

script:
  - ant clean build
  - and deploy
  - ant run


